(executable
 (name wordcount)
 (modules wordcount)
 (libraries dataflowlib))

(executable
 (name wordcountjson)
 (modules wordcountjson)
 (libraries dataflowlib))

(executable
 (name wordcount_parallel)
 (modules wordcount_parallel)
 (libraries dataflowlib))

(executable
 (name wordcount_benchmark)
 (modules wordcount_benchmark)
 (libraries dataflowlib))

(executable
 (name wordcount_new_shards)
 (modules wordcount_new_shards)
 (libraries dataflowlib nodeShard))

(executable
 (name kmeans)
 (modules kmeans)
 (libraries dataflowlib nodes))

(executable
 (name matrix_factorization)
 (modules matrix_factorization)
 (libraries dataflowlib nodes))

(executable
 (name kmeans_shards)
 (modules kmeans_shards)
 (libraries dataflowlib nodeShard))
