(executable
 (name wordcount)
 (modules wordcount)
 (libraries dataflowlib))

(executable
 (name wordcountjson)
 (modules wordcountjson)
 (libraries dataflowlib))

(executable
 (name wordcount_parallel)
 (modules wordcount_parallel)
 (libraries dataflowlib))

(executable
 (name wordcount_benchmark)
 (modules wordcount_benchmark)
 (libraries dataflowlib))

(executable
 (name wordcount_new)
 (modules wordcount_new)
 (libraries dataflowlib nodes))
